apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel.fullname" . }}-backend
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: http
